### ISSUE TITLE
refactor-1주차-milestone,docs

### ISSUE THREAD

**Issue by JuGeonjeong** [JuGeonjeong/hhp-concert#26]
## refactor STEP.1
- [x] 프로젝트 Milestone
- [x] 요구사항 별 분석 자료
- [x] 시퀀스 다이어그램, 플로우 차트 등
- [x] 자료들을 리드미에 정리
- [x] ERD 설계 자료
- [x] API 명세 및 Mock API 작성
---
### refactor 정리하기
- [x] milestone: 테이블로 작성 -> github 프로젝트 마일스톤 정리
- [x] readme: 문서, 사진 일괄 나열 -> 목차로 정리
